### PR TITLE
Skip failing tests

### PR DESCRIPTION
**Pull request by tvhong**

### CODE REVIEW

**Comment by llinauer** [comment]
+1 for skipping tests we know to fail.
However, do we know why they fail or how we can fix that?

**Comment by shaheenahmedc** [comment]
Just looked at one of the failing tests. It appears "cat" doesn't get generated, as intended, in `test_token_identity_prompt_early`. I agree with skipping tests for now. Would like to look into this again when writing up the token identity tutorial. 
image
image

**Comment by shaheenahmedc** [comment]
`test_token_identity_prompt` has the same problem, only difference is it patches into the last layer, as opposed to an early layer in `test_token_identity_prompt_early`

**Comment by shaheenahmedc** [comment]
Just looking at `test_over` quickly, I think it fails because of this change in `patchscope.Patchscope.over`:
image
The indexing of the values is off in the test as a result:
image

What's the best way to proceed, merge this PR and shall I write up an issue for this?

**Comment by tvhong** [comment]
I’d say merge this first fix the tests in a separate PR. I think this change is strictly better than the current state of running failing tests.

We can create GH issues for the failing tests if we can’t figure out why they fail yet.

One thing I notice is that the autobuild for this project has been failing for a while. I believe this is part of the reasons.

**Comment by tvhong** [comment]
Lol. GPT-2 predicts that the next token of "it has whiskers and a tail. it domesticated itself. it is a species of" is "bird".

That's probably why the concept of "cat" never appears in the token identity prompt test.

image

**Pull request merged**
